# Outgoing email settings

production:
  delivery_method: :smtp
  smtp_settings:
    address: smtp.inmail.sk
    port: 25
    domain: bughunters.heroku.com
    authentication: :login
    user_name: "bughunters@inmail.sk"
    password: "bug_hunter"

development:
  delivery_method: :smtp
  smtp_settings:
    address: smtp.inmail.sk
    port: 25
    domain: bughunters.heroku.com
    authentication: :login
    user_name: "bughunters@inmail.sk"
    password: "bug_hunter"

