# Outgoing email settings

production:
  delivery_method: :smtp
  smtp_settings:
    address: smtp-out.xnet.cz
    port: 25
    domain: bughunters.free.railshosting.cz

development:
  delivery_method: :smtp
  smtp_settings:
    address: smtp-out.xnet.cz
    port: 25
    domain: bughunters.free.railshosting.cz

